services:
  - type: web
    name: tracker-gastos-tarjeta
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildFilter:
      paths:
      - pages/**
      - styles/**
      - public/**
      - next.config.js
      - package.json 